# Site settings
title: pablodp.com
email: pablozxt@gmail.com
twitter_username: pablozxt
github_username:  pablozxt
paginate: 2
description: >
  I am Pablo Perez, an engineer, web developer, father of three and spaniard living in Los Angeles.
url: "http://pablodp.com"

# Build settings
markdown: kramdown
exclude: [
	bower.json,
	config.rb,
	Gemfile,
	Gemfile.lock,
	README.md,
	package.json,
	scss,
	node_modules,
	gruntfile.js,
	humans.txt,
	robots.txt,
	feed.xml
]
gems: [jekyll-compass, octopress-autoprefixer, modular-scale, toolkit]
sass:
  style: :nested
