# Site settings
title: pablodp.net
email: pablodp@outlook.com
description: >
  I am Pablo Perez, an engineer, web developer, father of three and
  spaniard living in Los Angeles. And this is my site.
url: "http://pablodp.net"
twitter_username: pablozxt
github_username:  pablozxt

# Build settings
markdown: kramdown
exclude: [
	bower.json,
	config.rb,
	Gemfile,
	Gemfile.lock,
	README.md,
	package.json,
	scss,
	node_modules,
	gruntfile.js,
	humans.txt,
	robots.txt,
	feed.xml
]
gems: [jekyll-compass]
sass:
  style: :nested
